**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [6]:
## your code(for different question use different cells)
##like Q.1.1
import numpy
array = [0]*10
print(array)

array = numpy.array([0]*10)
print(array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0 0 0 0 0 0 0 0 0 0]


In [3]:
#Q.1.2
import numpy
array = [5]*10
print(array)

array = numpy.array([5]*10)
print(array)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
[5 5 5 5 5 5 5 5 5 5]


In [5]:
#Q.1.3
import numpy

matrix = [[a+b*3 for a in range(3)] for b in range(3)]
print(matrix)

matrix = numpy.matrix([[a+b*3 for a in range(3)] for b in range(3)])
print(matrix)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#Q.1.4
import numpy
print("The random number is:", numpy.random.rand())

The random number is: 0.9236711415468188


In [9]:
#Q.1.5
import numpy
# 22 so that 20 points excluding end points are there
points = numpy.linspace(0,1,22)
print(points)


[0.         0.04761905 0.0952381  0.14285714 0.19047619 0.23809524
 0.28571429 0.33333333 0.38095238 0.42857143 0.47619048 0.52380952
 0.57142857 0.61904762 0.66666667 0.71428571 0.76190476 0.80952381
 0.85714286 0.9047619  0.95238095 1.        ]


In [10]:
#Q.1.6
def number_of_vowels(str):
  return sum([str.count(a) for a in "aeiou"])
print("number of vowels are:", number_of_vowels(input("enter the string: ")))

enter the string: hello i am the best
number of vowels are: 6


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##your code
#Q2.1
numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
#I am not sure what you mean by this since even numbers arent necissarily on the even indices so slicing wont really help
#For this particular array I could just observe and brute force write the code like below
print(numbers[0:5:2]+numbers[5:10:2]+numbers[11:])
#But a general soln would be
print([a for a in numbers if not a%2])

In [30]:
#Q2.2
import numpy
#end points are not included
matc = numpy.matrix([[numpy.random.randint(11,100) for i in range(4)] for j in range(5)])
print(matc)

#Q2.3
print()
print(matc[0:3, 0:2])

#Q2.4
print()
one_d_arr = matc.flatten()
fourxfivematc = numpy.reshape(one_d_arr, (4,5))
print(fourxfivematc)

#Q2.5
print()
one_d_arr = fourxfivematc.flatten()
print(one_d_arr)

[[77 97 26 51]
 [18 32 81 45]
 [18 64 82 24]
 [35 42 31 50]
 [14 81 48 43]]

[[77 97]
 [18 32]
 [18 64]]

[[77 97 26 51 18]
 [32 81 45 18 64]
 [82 24 35 42 31]
 [50 14 81 48 43]]

[[77 97 26 51 18 32 81 45 18 64 82 24 35 42 31 50 14 81 48 43]]


In [36]:
#Q2.6
import numpy
#end points are not included
matc1 = numpy.matrix([[numpy.random.randint(11,100) for i in range(4)] for j in range(5)])
matc2 = numpy.matrix([[numpy.random.randint(11,100) for i in range(5)] for j in range(4)])
matcres = numpy.matmul(matc2, matc1)
print("matrix 1 (4x5):\n",matc1)
print()
print("matrix 2 (5x4):\n",matc2)
print()
print("matrix result(4x4):\n",matcres)


matrix 1 (4x5):
 [[73 30 31 95]
 [71 98 52 65]
 [19 95 31 52]
 [81 99 21 41]
 [13 88 86 21]]

matrix 2 (5x4):
 [[52 73 50 21 80]
 [55 13 37 44 94]
 [94 81 90 89 36]
 [24 51 96 33 29]]

matrix result(4x4):
 [[12670 22583 14279 14826]
 [10427 19067 12536 11772]
 [22000 31287 14881 23280]
 [10247 20657  9559 12549]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
#The input should be numpy matrices
import numpy
def Validmult(m1, m2):
  if m1.shape[1] == m2.shape[0]:
    return True
  return False

(ii) Using loops (without using numpy)

In [75]:
#The inputs here are normal 2D arrays

def Validmult(m1, m2):
  if len(m1[0]) == len(m2):
    return True
  return False

def multiplymatrices(m1, m2):
  if not Validmult(m1, m2):
    print("ERROR: Given Multiplication is not valid")
    return None
  res = []
  for i in range(len(m1)):
    a = []
    for j in range(len(m2[0])):
      element = 0
      for k in range(len(m1[0])):
        element += m1[i][k]*m2[k][j]
      a.append(element)
    res.append(a)
  return res

matc1 = [[numpy.random.randint(11,100) for i in range(4)] for j in range(5)]
matc2 = [[numpy.random.randint(11,100) for i in range(5)] for j in range(4)]
print(matc1)
print(matc2)
print(multiplymatrices(matc1, matc2))


[[28, 77, 72, 69], [37, 18, 93, 36], [58, 76, 52, 58], [21, 69, 33, 69], [97, 17, 84, 52]]
[[63, 21, 28, 95, 43], [60, 93, 21, 66, 62], [63, 52, 26, 54, 71], [39, 15, 38, 20, 11]]
[[13611, 12528, 6895, 13010, 11849], [10674, 7827, 5200, 10445, 9706], [13752, 11860, 6776, 14494, 11536], [10233, 9609, 5517, 9711, 8283], [14451, 8766, 7233, 15913, 11761]]


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [66]:
X = [1,2,3,4,5]
Y = [2,4,5,4,5]

x_m = sum(X)/len(X)
y_m = sum(Y)/len(Y)

m = sum([(X[i]-x_m)*(Y[i]-y_m) for i in range(len(X))])/sum([(X[i]-x_m)**2 for i in range(len(X))])
c = y_m - m*x_m

print("mean of X:",x_m)
print("mean of Y:",y_m)
print("slope:",m)
print("intercept",c)
print("actual Y   :",Y)
print("predicted Y:",[round(m*X[i]+c,2) for i in range(len(X))])

mean of X: 3.0
mean of Y: 4.0
slope: 0.6
intercept 2.2
actual Y   : [2, 4, 5, 4, 5]
predicted Y: [2.8, 3.4, 4.0, 4.6, 5.2]


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [104]:
import pandas
import numpy
ses = pandas.read_csv("/performance_dataset.csv")
#backup
ses.to_csv('data_backup.csv', index=False)

#looking at the first 15 rows
print(ses.head(15))

#adding 1 to commute_time_mins because why not
ses['commute_time_mins'] = ses['commute_time_mins'] + 1
print(ses.head(2))

#printing 10th row and the element with index [0,0] ie the first cell
print(ses.iloc[9])
print(ses.iloc[0,0])

#replacing all null values with -1
for i in [(row, col) for row, col in zip(*numpy.where(ses.isnull()))]:
  ses.iloc[i[0],i[1]] = -1
print(ses.head(1))

#dropping school-type
ses = ses.drop("school_type", axis = 1)
print(ses.head(1))

#There is no column which has string values in the given document but below is how you would do it
try:
  print(ses[ses["locker_number"].str.startswith("1")].head(1))
except:
  print("Gave an error since the column is not a string")

#adding unproductive_hours
ses["unproductive_hours_weekly"] = ses["commute_time_mins"]/60*7 + ses["screen_time_weekly"]
print(ses.head(1))




    hours_studied  attendance_percent  parent_education  internet_access  \
0        4.743108           79.781453               3.0              NaN   
1       10.992036           97.666558               3.0              1.0   
2        8.848935           57.950598               2.0              0.0   
3        3.481116           84.636899               0.0              0.0   
4        6.264199           58.081774               1.0              0.0   
5       12.954310           66.696510               3.0              0.0   
6        0.719962           60.457167               2.0              0.0   
7        6.713262           63.990601               1.0              1.0   
8       11.797809           84.437431               3.0              1.0   
9        5.399779           76.552077               2.0              0.0   
10       5.963342           54.191108               0.0              1.0   
11       7.715873           55.539041               0.0              0.0   
12      12.4