**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
## your code(for different question use different cells)
##like Q.1.
#1
import numpy as np
arr1=np.array([0,0,0,0,0,0,0,0,0,0])
arr2=np.array([5,5,5,5,5,5,5,5,5,5])
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3.shape)
from numpy import random
x= random.rand()
print(x)
arr4=np.arange(20)
print(arr4)
string1=input("enter string ")
count =0;
vowels="AEIOUaeiou"
for x in string1:
  if x in vowels:
    count=count+1;
print(count)


(2, 2, 2)
0.025907084904555067
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
enter stringsamman
2


In [ ]:
#Q.1.2
.....

**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##your code
import numpy as np
given_array = np.array([12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48])
even_numbers= []
for x in given_array:
  if x%2==0:
    even_numbers.append(x)
numpyeven=np.array(even_numbers)
print(numpyeven)
boolean_mask = (given_array % 2 == 0)
even_numbers2=given_array[boolean_mask]
print(even_numbers2)
from numpy import random
arr2=np.random.randint(low=10,high=101,size=(5,4))
print(arr2)
sliced_array=arr2[0:3,0:2]
print(sliced_array)
flattened_array=arr2.reshape(-1)
arr45=arr2.reshape(4,5)
print(arr45)
print(flattened_array)
arr3=np.random.randint(100,size=(4,3))
mul_arr=arr2@arr3
print(mul_arr)

[ 12  44 102  -8  56  90 -24  48]
[ 12  44 102  -8  56  90 -24  48]
[[54 13 21 57]
 [98 15 45 51]
 [41 46 45 77]
 [41 22 18 67]
 [39 21 64 67]]
[[54 13]
 [98 15]
 [41 46]]
[[54 13 21 57 98]
 [15 45 51 41 46]
 [45 77 41 22 18]
 [67 39 21 64 67]]
[54 13 21 57 98 15 45 51 41 46 45 77 41 22 18 67 39 21 64 67]
[[ 7813  8026  7104]
 [13839 13076 10198]
 [10555 11080 11070]
 [ 6949  7541  7517]
 [10581 11078  9219]]


**Q.3**

(i) Check if matrix multiplication is valid

In [ ]:
import numpy as np
arr1=np.random.randint(100,size=(4,3))
arr2=np.random.randint(100,size=(3,4))
size1=arr1.shape;
size2=np.array(arr2.shape);
if(size1[1]==size2[0]):
  print("yes")

yes


(ii) Using loops (without using numpy)

In [ ]:
arr1=np.random.randint(100,size=(4,3))
arr2=np.random.randint(100,size=(3,4))
col=0
for y in arr1[0]:
  col = col +1
row =0;
for x in  arr2:
  row =row +1
if (col==row):
  print("yes")


yes


**Q.4**
(i) Given:

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [ ]:
X = [1,2,3,4,5]
Y = [2,4,5,4,5]
sum=0
count=0
for x in X:
  sum = sum+x
  count = count +1
mean = sum/count
print(mean)
sum2=0
count2=0
for y in Y:
  sum2=sum2+y
  count2=count2+1
mean2= sum2/count2
print(mean2)
s1=0
s2=0
s3=0
for x in X:
 s3=s3+(x-mean)*(x-mean)
for i in range(5) :
  s1=s1+(X[i]-mean)*(Y[i]-mean2)
#  s2=s2+(y-mean2)
m=s1/s3
print(m)
c=mean2-mean*m
print(c)
Yp=[]
for x in X:
  Yp.append(m*x+c)
print (Yp)


3.0
4.0
0.6
2.2
[2.8000000000000003, 3.4000000000000004, 4.0, 4.6, 5.2]


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [13]:
import pandas as pd
df=pd.read_csv('performance_dataset.csv')

df.fillna(130,inplace=True)
# print(df.to_string())
df.corr()

hours_studied  attendance_percent  parent_education  \
hours_studied              1.000000           -0.004058          0.005745   
attendance_percent        -0.004058            1.000000          0.010094   
parent_education           0.005745            0.010094          1.000000   
internet_access            0.001456            0.024453         -0.014644   
school_type                0.017833           -0.008112         -0.015126   
sports_participation       0.003102            0.005116          0.007349   
part_time_job             -0.015131           -0.030675          0.010484   
siblings                   0.008874            0.001872          0.002303   
commute_time_mins          0.027776            0.024330         -0.006800   
favorite_subject           0.005946           -0.008165         -0.007633   
club_member                0.003236            0.023189          0.027615   
self_study_hours          -0.028703           -0.012456          0.006636   
pet_count                  0.024132           -0.013851         -0.019170   
locker_number             -0.025270            0.000857         -0.007482   
bus_route                  0.017528           -0.000741          0.018056   
screen_time_weekly         0.001550           -0.030227         -0.007342   
height_cm                  0.011274           -0.015874         -0.025152   
weight_kg                 -0.000852            0.006298         -0.019652   
lunch_type                 0.009520           -0.006687         -0.031358   
math_tutor                 0.014459            0.016603          0.032432   
reading_habit             -0.002171            0.009678         -0.006239   
video_game_freq           -0.014800            0.012760          0.001347   
music_hours_weekly        -0.011730           -0.000092         -0.018163   
parent_meeting_freq       -0.005589           -0.006082          0.006266   
uniform                    0.001275           -0.022631          0.001599   

                      internet_access  school_type  sports_participation  \
hours_studied                0.001456     0.017833              0.003102   
attendance_percent           0.024453    -0.008112              0.005116   
parent_education            -0.014644    -0.015126              0.007349   
internet_access              1.000000    -0.006690             -0.002310   
school_type                 -0.006690     1.000000              0.032047   
sports_participation        -0.002310     0.032047              1.000000   
part_time_job               -0.006224    -0.026955              0.014402   
siblings                    -0.010655     0.002756              0.002350   
commute_time_mins            0.001259     0.030773              0.002019   
favorite_subject             0.009935    -0.001571             -0.002685   
club_member                 -0.002161    -0.010513             -0.014097   
self_study_hours             0.004981    -0.006195              0.002705   
pet_count                    0.009911    -0.002809              0.007092   
locker_number               -0.010736    -0.002031             -0.005770   
bus_route                    0.000280     0.005101             -0.000915   
screen_time_weekly          -0.031517    -0.001212              0.010625   
height_cm                   -0.017837     0.004987              0.000991   
weight_kg                    0.039652     0.011591             -0.036946   
lunch_type                   0.010409     0.001851             -0.005998   
math_tutor                   0.005455     0.001593             -0.032186   
reading_habit               -0.001780     0.052902             -0.014910   
video_game_freq             -0.006074    -0.010385              0.024683   
music_hours_weekly          -0.018407    -0.016289              0.001600   
parent_meeting_freq          0.006355     0.023673              0.011381   
uniform                     -0.018549     0.005985             -0.002346   

                      part_time_job  sibli

In [24]:
import pandas as pd
df=pd.read_csv('performance_dataset.csv')
print(df.iloc[345,0])
df.drop(labels=0,axis=0,inplace=True)
print(df)

8.26319139159973
      hours_studied  attendance_percent  parent_education  internet_access  \
1         10.992036           97.666558               3.0              1.0   
2          8.848935           57.950598               2.0              0.0   
3          3.481116           84.636899               0.0              0.0   
4          6.264199           58.081774               1.0              0.0   
5         12.954310           66.696510               3.0              0.0   
...             ...                 ...               ...              ...   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_

In [25]:
import pandas as pd
df=pd.read_csv('performance_dataset.csv')
studious = df[df['hours_studied'] > 7]
print(studious)

      hours_studied  attendance_percent  parent_education  internet_access  \
1         10.992036           97.666558               3.0              1.0   
2          8.848935           57.950598               2.0              0.0   
5         12.954310           66.696510               3.0              0.0   
8         11.797809           84.437431               3.0              1.0   
11         7.715873           55.539041               0.0              0.0   
...             ...                 ...               ...              ...   
4988      10.973572           83.086284               2.0              1.0   
4989       9.986863           66.934409               0.0              1.0   
4991      10.861546           55.723819               1.0              1.0   
4993      10.335344          100.000000               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   

      school_type  sports_participation  part_time_job  sibling

In [26]:
import pandas as pd
df=pd.read_csv('performance_dataset.csv')
df['total_hours_studied']=df['hours_studied']+df['self_study_hours']
print(df)

      hours_studied  attendance_percent  parent_education  internet_access  \
0          4.743108           79.781453               3.0              NaN   
1         10.992036           97.666558               3.0              1.0   
2          8.848935           57.950598               2.0              0.0   
3          3.481116           84.636899               0.0              0.0   
4          6.264199           58.081774               1.0              0.0   
...             ...                 ...               ...              ...   
4995       4.633189           66.031236               0.0              1.0   
4996       3.744086           54.031024               2.0              0.0   
4997       2.420855           67.916004               3.0              0.0   
4998      10.741467           83.729465               2.0              NaN   
4999       3.938481           89.559193               2.0              0.0   

      school_type  sports_participation  part_time_job  sibling